#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COLLEGEPORTAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbmsProject")]
	public partial class dbmsProjectDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertloginn_student(loginn_student instance);
    partial void Updateloginn_student(loginn_student instance);
    partial void Deleteloginn_student(loginn_student instance);
    partial void Insertloginn_Teacher(loginn_Teacher instance);
    partial void Updateloginn_Teacher(loginn_Teacher instance);
    partial void Deleteloginn_Teacher(loginn_Teacher instance);
    partial void Insertattend(attend instance);
    partial void Updateattend(attend instance);
    partial void Deleteattend(attend instance);
    partial void Insertteacher(teacher instance);
    partial void Updateteacher(teacher instance);
    partial void Deleteteacher(teacher instance);
    partial void InsertSubject_Urdu(Subject_Urdu instance);
    partial void UpdateSubject_Urdu(Subject_Urdu instance);
    partial void DeleteSubject_Urdu(Subject_Urdu instance);
    partial void InsertSubject_Pk(Subject_Pk instance);
    partial void UpdateSubject_Pk(Subject_Pk instance);
    partial void DeleteSubject_Pk(Subject_Pk instance);
    partial void InsertSubject_Phy(Subject_Phy instance);
    partial void UpdateSubject_Phy(Subject_Phy instance);
    partial void DeleteSubject_Phy(Subject_Phy instance);
    partial void InsertSubject_Math(Subject_Math instance);
    partial void UpdateSubject_Math(Subject_Math instance);
    partial void DeleteSubject_Math(Subject_Math instance);
    partial void InsertSubject_English(Subject_English instance);
    partial void UpdateSubject_English(Subject_English instance);
    partial void DeleteSubject_English(Subject_English instance);
    partial void InsertSubject_Computer(Subject_Computer instance);
    partial void UpdateSubject_Computer(Subject_Computer instance);
    partial void DeleteSubject_Computer(Subject_Computer instance);
    partial void InsertMark(Mark instance);
    partial void UpdateMark(Mark instance);
    partial void DeleteMark(Mark instance);
    partial void Insertloginn_Admin(loginn_Admin instance);
    partial void Updateloginn_Admin(loginn_Admin instance);
    partial void Deleteloginn_Admin(loginn_Admin instance);
    partial void Insertstudent(student instance);
    partial void Updatestudent(student instance);
    partial void Deletestudent(student instance);
    #endregion
		
		public dbmsProjectDataContext() : 
				base(global::COLLEGEPORTAL.Properties.Settings.Default.dbmsProjectConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbmsProjectDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbmsProjectDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbmsProjectDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbmsProjectDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<loginn_student> loginn_students
		{
			get
			{
				return this.GetTable<loginn_student>();
			}
		}
		
		public System.Data.Linq.Table<loginn_Teacher> loginn_Teachers
		{
			get
			{
				return this.GetTable<loginn_Teacher>();
			}
		}
		
		public System.Data.Linq.Table<attend> attends
		{
			get
			{
				return this.GetTable<attend>();
			}
		}
		
		public System.Data.Linq.Table<teacher> teachers
		{
			get
			{
				return this.GetTable<teacher>();
			}
		}
		
		public System.Data.Linq.Table<Subject_Urdu> Subject_Urdus
		{
			get
			{
				return this.GetTable<Subject_Urdu>();
			}
		}
		
		public System.Data.Linq.Table<Subject_Pk> Subject_Pks
		{
			get
			{
				return this.GetTable<Subject_Pk>();
			}
		}
		
		public System.Data.Linq.Table<Subject_Phy> Subject_Phies
		{
			get
			{
				return this.GetTable<Subject_Phy>();
			}
		}
		
		public System.Data.Linq.Table<Subject_Math> Subject_Maths
		{
			get
			{
				return this.GetTable<Subject_Math>();
			}
		}
		
		public System.Data.Linq.Table<Subject_English> Subject_Englishes
		{
			get
			{
				return this.GetTable<Subject_English>();
			}
		}
		
		public System.Data.Linq.Table<Subject_Computer> Subject_Computers
		{
			get
			{
				return this.GetTable<Subject_Computer>();
			}
		}
		
		public System.Data.Linq.Table<Mark> Marks
		{
			get
			{
				return this.GetTable<Mark>();
			}
		}
		
		public System.Data.Linq.Table<loginn_Admin> loginn_Admins
		{
			get
			{
				return this.GetTable<loginn_Admin>();
			}
		}
		
		public System.Data.Linq.Table<student> students
		{
			get
			{
				return this.GetTable<student>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.loginn_student")]
	public partial class loginn_student : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _user_namee;
		
		private string _user_pass;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_nameeChanging(string value);
    partial void Onuser_nameeChanged();
    partial void Onuser_passChanging(string value);
    partial void Onuser_passChanged();
    #endregion
		
		public loginn_student()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_namee", DbType="VarChar(50)", IsPrimaryKey=true)]
		public string user_namee
		{
			get
			{
				return this._user_namee;
			}
			set
			{
				if ((this._user_namee != value))
				{
					this.Onuser_nameeChanging(value);
					this.SendPropertyChanging();
					this._user_namee = value;
					this.SendPropertyChanged("user_namee");
					this.Onuser_nameeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_pass", DbType="VarChar(50)")]
		public string user_pass
		{
			get
			{
				return this._user_pass;
			}
			set
			{
				if ((this._user_pass != value))
				{
					this.Onuser_passChanging(value);
					this.SendPropertyChanging();
					this._user_pass = value;
					this.SendPropertyChanged("user_pass");
					this.Onuser_passChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.loginn_Teacher")]
	public partial class loginn_Teacher : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _user_namee;
		
		private string _user_pass;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_nameeChanging(string value);
    partial void Onuser_nameeChanged();
    partial void Onuser_passChanging(string value);
    partial void Onuser_passChanged();
    #endregion
		
		public loginn_Teacher()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_namee", DbType="VarChar(50)", IsPrimaryKey=true)]
		public string user_namee
		{
			get
			{
				return this._user_namee;
			}
			set
			{
				if ((this._user_namee != value))
				{
					this.Onuser_nameeChanging(value);
					this.SendPropertyChanging();
					this._user_namee = value;
					this.SendPropertyChanged("user_namee");
					this.Onuser_nameeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_pass", DbType="VarChar(50)")]
		public string user_pass
		{
			get
			{
				return this._user_pass;
			}
			set
			{
				if ((this._user_pass != value))
				{
					this.Onuser_passChanging(value);
					this.SendPropertyChanging();
					this._user_pass = value;
					this.SendPropertyChanged("user_pass");
					this.Onuser_passChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.attend")]
	public partial class attend : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Student_ID;
		
		private string _Student_Name;
		
		private System.Nullable<int> _A;
		
		private System.Nullable<int> _P;
		
		private string _Subjects;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStudent_IDChanging(int value);
    partial void OnStudent_IDChanged();
    partial void OnStudent_NameChanging(string value);
    partial void OnStudent_NameChanged();
    partial void OnAChanging(System.Nullable<int> value);
    partial void OnAChanged();
    partial void OnPChanging(System.Nullable<int> value);
    partial void OnPChanged();
    partial void OnSubjectsChanging(string value);
    partial void OnSubjectsChanged();
    #endregion
		
		public attend()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Student_ID
		{
			get
			{
				return this._Student_ID;
			}
			set
			{
				if ((this._Student_ID != value))
				{
					this.OnStudent_IDChanging(value);
					this.SendPropertyChanging();
					this._Student_ID = value;
					this.SendPropertyChanged("Student_ID");
					this.OnStudent_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student_Name", DbType="VarChar(50)")]
		public string Student_Name
		{
			get
			{
				return this._Student_Name;
			}
			set
			{
				if ((this._Student_Name != value))
				{
					this.OnStudent_NameChanging(value);
					this.SendPropertyChanging();
					this._Student_Name = value;
					this.SendPropertyChanged("Student_Name");
					this.OnStudent_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A", DbType="Int")]
		public System.Nullable<int> A
		{
			get
			{
				return this._A;
			}
			set
			{
				if ((this._A != value))
				{
					this.OnAChanging(value);
					this.SendPropertyChanging();
					this._A = value;
					this.SendPropertyChanged("A");
					this.OnAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P", DbType="Int")]
		public System.Nullable<int> P
		{
			get
			{
				return this._P;
			}
			set
			{
				if ((this._P != value))
				{
					this.OnPChanging(value);
					this.SendPropertyChanging();
					this._P = value;
					this.SendPropertyChanged("P");
					this.OnPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subjects", DbType="VarChar(50)")]
		public string Subjects
		{
			get
			{
				return this._Subjects;
			}
			set
			{
				if ((this._Subjects != value))
				{
					this.OnSubjectsChanging(value);
					this.SendPropertyChanging();
					this._Subjects = value;
					this.SendPropertyChanged("Subjects");
					this.OnSubjectsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.teacher")]
	public partial class teacher : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Teacher_Reg;
		
		private string _Teacher_name;
		
		private string _Teacher_subjects;
		
		private System.Nullable<int> _Teacher_Fees;
		
		private string _Class_Teacher;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTeacher_RegChanging(int value);
    partial void OnTeacher_RegChanged();
    partial void OnTeacher_nameChanging(string value);
    partial void OnTeacher_nameChanged();
    partial void OnTeacher_subjectsChanging(string value);
    partial void OnTeacher_subjectsChanged();
    partial void OnTeacher_FeesChanging(System.Nullable<int> value);
    partial void OnTeacher_FeesChanged();
    partial void OnClass_TeacherChanging(string value);
    partial void OnClass_TeacherChanged();
    #endregion
		
		public teacher()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Teacher_Reg", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Teacher_Reg
		{
			get
			{
				return this._Teacher_Reg;
			}
			set
			{
				if ((this._Teacher_Reg != value))
				{
					this.OnTeacher_RegChanging(value);
					this.SendPropertyChanging();
					this._Teacher_Reg = value;
					this.SendPropertyChanged("Teacher_Reg");
					this.OnTeacher_RegChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Teacher_name", DbType="VarChar(50)")]
		public string Teacher_name
		{
			get
			{
				return this._Teacher_name;
			}
			set
			{
				if ((this._Teacher_name != value))
				{
					this.OnTeacher_nameChanging(value);
					this.SendPropertyChanging();
					this._Teacher_name = value;
					this.SendPropertyChanged("Teacher_name");
					this.OnTeacher_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Teacher_subjects", DbType="VarChar(50)")]
		public string Teacher_subjects
		{
			get
			{
				return this._Teacher_subjects;
			}
			set
			{
				if ((this._Teacher_subjects != value))
				{
					this.OnTeacher_subjectsChanging(value);
					this.SendPropertyChanging();
					this._Teacher_subjects = value;
					this.SendPropertyChanged("Teacher_subjects");
					this.OnTeacher_subjectsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Teacher_Fees", DbType="Int")]
		public System.Nullable<int> Teacher_Fees
		{
			get
			{
				return this._Teacher_Fees;
			}
			set
			{
				if ((this._Teacher_Fees != value))
				{
					this.OnTeacher_FeesChanging(value);
					this.SendPropertyChanging();
					this._Teacher_Fees = value;
					this.SendPropertyChanged("Teacher_Fees");
					this.OnTeacher_FeesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Class_Teacher", DbType="VarChar(50)")]
		public string Class_Teacher
		{
			get
			{
				return this._Class_Teacher;
			}
			set
			{
				if ((this._Class_Teacher != value))
				{
					this.OnClass_TeacherChanging(value);
					this.SendPropertyChanging();
					this._Class_Teacher = value;
					this.SendPropertyChanged("Class_Teacher");
					this.OnClass_TeacherChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Subject_Urdu")]
	public partial class Subject_Urdu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Student_Name;
		
		private System.Nullable<int> _Marks;
		
		private System.Nullable<int> _First_Term_marks;
		
		private System.Nullable<int> _Second_Term_marks;
		
		private System.Nullable<int> _Final_Term_marks;
		
		private System.Nullable<decimal> _Avgg;
		
		private string _Result;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnStudent_NameChanging(string value);
    partial void OnStudent_NameChanged();
    partial void OnMarksChanging(System.Nullable<int> value);
    partial void OnMarksChanged();
    partial void OnFirst_Term_marksChanging(System.Nullable<int> value);
    partial void OnFirst_Term_marksChanged();
    partial void OnSecond_Term_marksChanging(System.Nullable<int> value);
    partial void OnSecond_Term_marksChanged();
    partial void OnFinal_Term_marksChanging(System.Nullable<int> value);
    partial void OnFinal_Term_marksChanged();
    partial void OnAvggChanging(System.Nullable<decimal> value);
    partial void OnAvggChanged();
    partial void OnResultChanging(string value);
    partial void OnResultChanged();
    #endregion
		
		public Subject_Urdu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student_Name", DbType="VarChar(50)")]
		public string Student_Name
		{
			get
			{
				return this._Student_Name;
			}
			set
			{
				if ((this._Student_Name != value))
				{
					this.OnStudent_NameChanging(value);
					this.SendPropertyChanging();
					this._Student_Name = value;
					this.SendPropertyChanged("Student_Name");
					this.OnStudent_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marks", DbType="Int")]
		public System.Nullable<int> Marks
		{
			get
			{
				return this._Marks;
			}
			set
			{
				if ((this._Marks != value))
				{
					this.OnMarksChanging(value);
					this.SendPropertyChanging();
					this._Marks = value;
					this.SendPropertyChanged("Marks");
					this.OnMarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First_Term_marks", DbType="Int")]
		public System.Nullable<int> First_Term_marks
		{
			get
			{
				return this._First_Term_marks;
			}
			set
			{
				if ((this._First_Term_marks != value))
				{
					this.OnFirst_Term_marksChanging(value);
					this.SendPropertyChanging();
					this._First_Term_marks = value;
					this.SendPropertyChanged("First_Term_marks");
					this.OnFirst_Term_marksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Second_Term_marks", DbType="Int")]
		public System.Nullable<int> Second_Term_marks
		{
			get
			{
				return this._Second_Term_marks;
			}
			set
			{
				if ((this._Second_Term_marks != value))
				{
					this.OnSecond_Term_marksChanging(value);
					this.SendPropertyChanging();
					this._Second_Term_marks = value;
					this.SendPropertyChanged("Second_Term_marks");
					this.OnSecond_Term_marksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Final_Term_marks", DbType="Int")]
		public System.Nullable<int> Final_Term_marks
		{
			get
			{
				return this._Final_Term_marks;
			}
			set
			{
				if ((this._Final_Term_marks != value))
				{
					this.OnFinal_Term_marksChanging(value);
					this.SendPropertyChanging();
					this._Final_Term_marks = value;
					this.SendPropertyChanged("Final_Term_marks");
					this.OnFinal_Term_marksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avgg", DbType="Decimal(1,1)")]
		public System.Nullable<decimal> Avgg
		{
			get
			{
				return this._Avgg;
			}
			set
			{
				if ((this._Avgg != value))
				{
					this.OnAvggChanging(value);
					this.SendPropertyChanging();
					this._Avgg = value;
					this.SendPropertyChanged("Avgg");
					this.OnAvggChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="VarChar(10)")]
		public string Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this.OnResultChanging(value);
					this.SendPropertyChanging();
					this._Result = value;
					this.SendPropertyChanged("Result");
					this.OnResultChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Subject_Pk")]
	public partial class Subject_Pk : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Student_Name;
		
		private System.Nullable<int> _Marks;
		
		private System.Nullable<int> _First_Term_marks;
		
		private System.Nullable<int> _Second_Term_marks;
		
		private System.Nullable<int> _Final_Term_marks;
		
		private System.Nullable<decimal> _Avgg;
		
		private string _Result;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnStudent_NameChanging(string value);
    partial void OnStudent_NameChanged();
    partial void OnMarksChanging(System.Nullable<int> value);
    partial void OnMarksChanged();
    partial void OnFirst_Term_marksChanging(System.Nullable<int> value);
    partial void OnFirst_Term_marksChanged();
    partial void OnSecond_Term_marksChanging(System.Nullable<int> value);
    partial void OnSecond_Term_marksChanged();
    partial void OnFinal_Term_marksChanging(System.Nullable<int> value);
    partial void OnFinal_Term_marksChanged();
    partial void OnAvggChanging(System.Nullable<decimal> value);
    partial void OnAvggChanged();
    partial void OnResultChanging(string value);
    partial void OnResultChanged();
    #endregion
		
		public Subject_Pk()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student_Name", DbType="VarChar(50)")]
		public string Student_Name
		{
			get
			{
				return this._Student_Name;
			}
			set
			{
				if ((this._Student_Name != value))
				{
					this.OnStudent_NameChanging(value);
					this.SendPropertyChanging();
					this._Student_Name = value;
					this.SendPropertyChanged("Student_Name");
					this.OnStudent_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marks", DbType="Int")]
		public System.Nullable<int> Marks
		{
			get
			{
				return this._Marks;
			}
			set
			{
				if ((this._Marks != value))
				{
					this.OnMarksChanging(value);
					this.SendPropertyChanging();
					this._Marks = value;
					this.SendPropertyChanged("Marks");
					this.OnMarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First_Term_marks", DbType="Int")]
		public System.Nullable<int> First_Term_marks
		{
			get
			{
				return this._First_Term_marks;
			}
			set
			{
				if ((this._First_Term_marks != value))
				{
					this.OnFirst_Term_marksChanging(value);
					this.SendPropertyChanging();
					this._First_Term_marks = value;
					this.SendPropertyChanged("First_Term_marks");
					this.OnFirst_Term_marksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Second_Term_marks", DbType="Int")]
		public System.Nullable<int> Second_Term_marks
		{
			get
			{
				return this._Second_Term_marks;
			}
			set
			{
				if ((this._Second_Term_marks != value))
				{
					this.OnSecond_Term_marksChanging(value);
					this.SendPropertyChanging();
					this._Second_Term_marks = value;
					this.SendPropertyChanged("Second_Term_marks");
					this.OnSecond_Term_marksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Final_Term_marks", DbType="Int")]
		public System.Nullable<int> Final_Term_marks
		{
			get
			{
				return this._Final_Term_marks;
			}
			set
			{
				if ((this._Final_Term_marks != value))
				{
					this.OnFinal_Term_marksChanging(value);
					this.SendPropertyChanging();
					this._Final_Term_marks = value;
					this.SendPropertyChanged("Final_Term_marks");
					this.OnFinal_Term_marksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avgg", DbType="Decimal(1,1)")]
		public System.Nullable<decimal> Avgg
		{
			get
			{
				return this._Avgg;
			}
			set
			{
				if ((this._Avgg != value))
				{
					this.OnAvggChanging(value);
					this.SendPropertyChanging();
					this._Avgg = value;
					this.SendPropertyChanged("Avgg");
					this.OnAvggChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="VarChar(10)")]
		public string Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this.OnResultChanging(value);
					this.SendPropertyChanging();
					this._Result = value;
					this.SendPropertyChanged("Result");
					this.OnResultChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Subject_Phy")]
	public partial class Subject_Phy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Student_Name;
		
		private System.Nullable<int> _Marks;
		
		private System.Nullable<int> _First_Term_marks;
		
		private System.Nullable<int> _Second_Term_marks;
		
		private System.Nullable<int> _Final_Term_marks;
		
		private System.Nullable<decimal> _Avgg;
		
		private string _Result;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnStudent_NameChanging(string value);
    partial void OnStudent_NameChanged();
    partial void OnMarksChanging(System.Nullable<int> value);
    partial void OnMarksChanged();
    partial void OnFirst_Term_marksChanging(System.Nullable<int> value);
    partial void OnFirst_Term_marksChanged();
    partial void OnSecond_Term_marksChanging(System.Nullable<int> value);
    partial void OnSecond_Term_marksChanged();
    partial void OnFinal_Term_marksChanging(System.Nullable<int> value);
    partial void OnFinal_Term_marksChanged();
    partial void OnAvggChanging(System.Nullable<decimal> value);
    partial void OnAvggChanged();
    partial void OnResultChanging(string value);
    partial void OnResultChanged();
    #endregion
		
		public Subject_Phy()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student_Name", DbType="VarChar(50)")]
		public string Student_Name
		{
			get
			{
				return this._Student_Name;
			}
			set
			{
				if ((this._Student_Name != value))
				{
					this.OnStudent_NameChanging(value);
					this.SendPropertyChanging();
					this._Student_Name = value;
					this.SendPropertyChanged("Student_Name");
					this.OnStudent_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marks", DbType="Int")]
		public System.Nullable<int> Marks
		{
			get
			{
				return this._Marks;
			}
			set
			{
				if ((this._Marks != value))
				{
					this.OnMarksChanging(value);
					this.SendPropertyChanging();
					this._Marks = value;
					this.SendPropertyChanged("Marks");
					this.OnMarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First_Term_marks", DbType="Int")]
		public System.Nullable<int> First_Term_marks
		{
			get
			{
				return this._First_Term_marks;
			}
			set
			{
				if ((this._First_Term_marks != value))
				{
					this.OnFirst_Term_marksChanging(value);
					this.SendPropertyChanging();
					this._First_Term_marks = value;
					this.SendPropertyChanged("First_Term_marks");
					this.OnFirst_Term_marksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Second_Term_marks", DbType="Int")]
		public System.Nullable<int> Second_Term_marks
		{
			get
			{
				return this._Second_Term_marks;
			}
			set
			{
				if ((this._Second_Term_marks != value))
				{
					this.OnSecond_Term_marksChanging(value);
					this.SendPropertyChanging();
					this._Second_Term_marks = value;
					this.SendPropertyChanged("Second_Term_marks");
					this.OnSecond_Term_marksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Final_Term_marks", DbType="Int")]
		public System.Nullable<int> Final_Term_marks
		{
			get
			{
				return this._Final_Term_marks;
			}
			set
			{
				if ((this._Final_Term_marks != value))
				{
					this.OnFinal_Term_marksChanging(value);
					this.SendPropertyChanging();
					this._Final_Term_marks = value;
					this.SendPropertyChanged("Final_Term_marks");
					this.OnFinal_Term_marksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avgg", DbType="Decimal(1,1)")]
		public System.Nullable<decimal> Avgg
		{
			get
			{
				return this._Avgg;
			}
			set
			{
				if ((this._Avgg != value))
				{
					this.OnAvggChanging(value);
					this.SendPropertyChanging();
					this._Avgg = value;
					this.SendPropertyChanged("Avgg");
					this.OnAvggChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="VarChar(10)")]
		public string Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this.OnResultChanging(value);
					this.SendPropertyChanging();
					this._Result = value;
					this.SendPropertyChanged("Result");
					this.OnResultChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Subject_Maths")]
	public partial class Subject_Math : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Student_Name;
		
		private System.Nullable<int> _Marks;
		
		private System.Nullable<int> _First_Term_marks;
		
		private System.Nullable<int> _Second_Term_marks;
		
		private System.Nullable<int> _Final_Term_marks;
		
		private System.Nullable<decimal> _Avgg;
		
		private string _Result;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnStudent_NameChanging(string value);
    partial void OnStudent_NameChanged();
    partial void OnMarksChanging(System.Nullable<int> value);
    partial void OnMarksChanged();
    partial void OnFirst_Term_marksChanging(System.Nullable<int> value);
    partial void OnFirst_Term_marksChanged();
    partial void OnSecond_Term_marksChanging(System.Nullable<int> value);
    partial void OnSecond_Term_marksChanged();
    partial void OnFinal_Term_marksChanging(System.Nullable<int> value);
    partial void OnFinal_Term_marksChanged();
    partial void OnAvggChanging(System.Nullable<decimal> value);
    partial void OnAvggChanged();
    partial void OnResultChanging(string value);
    partial void OnResultChanged();
    #endregion
		
		public Subject_Math()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student_Name", DbType="VarChar(50)")]
		public string Student_Name
		{
			get
			{
				return this._Student_Name;
			}
			set
			{
				if ((this._Student_Name != value))
				{
					this.OnStudent_NameChanging(value);
					this.SendPropertyChanging();
					this._Student_Name = value;
					this.SendPropertyChanged("Student_Name");
					this.OnStudent_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marks", DbType="Int")]
		public System.Nullable<int> Marks
		{
			get
			{
				return this._Marks;
			}
			set
			{
				if ((this._Marks != value))
				{
					this.OnMarksChanging(value);
					this.SendPropertyChanging();
					this._Marks = value;
					this.SendPropertyChanged("Marks");
					this.OnMarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First_Term_marks", DbType="Int")]
		public System.Nullable<int> First_Term_marks
		{
			get
			{
				return this._First_Term_marks;
			}
			set
			{
				if ((this._First_Term_marks != value))
				{
					this.OnFirst_Term_marksChanging(value);
					this.SendPropertyChanging();
					this._First_Term_marks = value;
					this.SendPropertyChanged("First_Term_marks");
					this.OnFirst_Term_marksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Second_Term_marks", DbType="Int")]
		public System.Nullable<int> Second_Term_marks
		{
			get
			{
				return this._Second_Term_marks;
			}
			set
			{
				if ((this._Second_Term_marks != value))
				{
					this.OnSecond_Term_marksChanging(value);
					this.SendPropertyChanging();
					this._Second_Term_marks = value;
					this.SendPropertyChanged("Second_Term_marks");
					this.OnSecond_Term_marksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Final_Term_marks", DbType="Int")]
		public System.Nullable<int> Final_Term_marks
		{
			get
			{
				return this._Final_Term_marks;
			}
			set
			{
				if ((this._Final_Term_marks != value))
				{
					this.OnFinal_Term_marksChanging(value);
					this.SendPropertyChanging();
					this._Final_Term_marks = value;
					this.SendPropertyChanged("Final_Term_marks");
					this.OnFinal_Term_marksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avgg", DbType="Decimal(1,1)")]
		public System.Nullable<decimal> Avgg
		{
			get
			{
				return this._Avgg;
			}
			set
			{
				if ((this._Avgg != value))
				{
					this.OnAvggChanging(value);
					this.SendPropertyChanging();
					this._Avgg = value;
					this.SendPropertyChanged("Avgg");
					this.OnAvggChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="VarChar(10)")]
		public string Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this.OnResultChanging(value);
					this.SendPropertyChanging();
					this._Result = value;
					this.SendPropertyChanged("Result");
					this.OnResultChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Subject_English")]
	public partial class Subject_English : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Student_Name;
		
		private System.Nullable<int> _Marks;
		
		private System.Nullable<int> _First_Term_marks;
		
		private System.Nullable<int> _Second_Term_marks;
		
		private System.Nullable<int> _Final_Term_marks;
		
		private System.Nullable<decimal> _Avgg;
		
		private string _Result;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnStudent_NameChanging(string value);
    partial void OnStudent_NameChanged();
    partial void OnMarksChanging(System.Nullable<int> value);
    partial void OnMarksChanged();
    partial void OnFirst_Term_marksChanging(System.Nullable<int> value);
    partial void OnFirst_Term_marksChanged();
    partial void OnSecond_Term_marksChanging(System.Nullable<int> value);
    partial void OnSecond_Term_marksChanged();
    partial void OnFinal_Term_marksChanging(System.Nullable<int> value);
    partial void OnFinal_Term_marksChanged();
    partial void OnAvggChanging(System.Nullable<decimal> value);
    partial void OnAvggChanged();
    partial void OnResultChanging(string value);
    partial void OnResultChanged();
    #endregion
		
		public Subject_English()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student_Name", DbType="VarChar(50)")]
		public string Student_Name
		{
			get
			{
				return this._Student_Name;
			}
			set
			{
				if ((this._Student_Name != value))
				{
					this.OnStudent_NameChanging(value);
					this.SendPropertyChanging();
					this._Student_Name = value;
					this.SendPropertyChanged("Student_Name");
					this.OnStudent_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marks", DbType="Int")]
		public System.Nullable<int> Marks
		{
			get
			{
				return this._Marks;
			}
			set
			{
				if ((this._Marks != value))
				{
					this.OnMarksChanging(value);
					this.SendPropertyChanging();
					this._Marks = value;
					this.SendPropertyChanged("Marks");
					this.OnMarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First_Term_marks", DbType="Int")]
		public System.Nullable<int> First_Term_marks
		{
			get
			{
				return this._First_Term_marks;
			}
			set
			{
				if ((this._First_Term_marks != value))
				{
					this.OnFirst_Term_marksChanging(value);
					this.SendPropertyChanging();
					this._First_Term_marks = value;
					this.SendPropertyChanged("First_Term_marks");
					this.OnFirst_Term_marksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Second_Term_marks", DbType="Int")]
		public System.Nullable<int> Second_Term_marks
		{
			get
			{
				return this._Second_Term_marks;
			}
			set
			{
				if ((this._Second_Term_marks != value))
				{
					this.OnSecond_Term_marksChanging(value);
					this.SendPropertyChanging();
					this._Second_Term_marks = value;
					this.SendPropertyChanged("Second_Term_marks");
					this.OnSecond_Term_marksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Final_Term_marks", DbType="Int")]
		public System.Nullable<int> Final_Term_marks
		{
			get
			{
				return this._Final_Term_marks;
			}
			set
			{
				if ((this._Final_Term_marks != value))
				{
					this.OnFinal_Term_marksChanging(value);
					this.SendPropertyChanging();
					this._Final_Term_marks = value;
					this.SendPropertyChanged("Final_Term_marks");
					this.OnFinal_Term_marksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avgg", DbType="Decimal(1,1)")]
		public System.Nullable<decimal> Avgg
		{
			get
			{
				return this._Avgg;
			}
			set
			{
				if ((this._Avgg != value))
				{
					this.OnAvggChanging(value);
					this.SendPropertyChanging();
					this._Avgg = value;
					this.SendPropertyChanged("Avgg");
					this.OnAvggChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="VarChar(10)")]
		public string Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this.OnResultChanging(value);
					this.SendPropertyChanging();
					this._Result = value;
					this.SendPropertyChanged("Result");
					this.OnResultChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Subject_Computer")]
	public partial class Subject_Computer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Student_Name;
		
		private System.Nullable<int> _Cmp_Marks;
		
		private System.Nullable<int> _First_Term_marks;
		
		private System.Nullable<int> _Second_Term_marks;
		
		private System.Nullable<int> _Final_Term_marks;
		
		private System.Nullable<decimal> _Avgg;
		
		private string _Result;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnStudent_NameChanging(string value);
    partial void OnStudent_NameChanged();
    partial void OnCmp_MarksChanging(System.Nullable<int> value);
    partial void OnCmp_MarksChanged();
    partial void OnFirst_Term_marksChanging(System.Nullable<int> value);
    partial void OnFirst_Term_marksChanged();
    partial void OnSecond_Term_marksChanging(System.Nullable<int> value);
    partial void OnSecond_Term_marksChanged();
    partial void OnFinal_Term_marksChanging(System.Nullable<int> value);
    partial void OnFinal_Term_marksChanged();
    partial void OnAvggChanging(System.Nullable<decimal> value);
    partial void OnAvggChanged();
    partial void OnResultChanging(string value);
    partial void OnResultChanged();
    #endregion
		
		public Subject_Computer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student_Name", DbType="VarChar(50)")]
		public string Student_Name
		{
			get
			{
				return this._Student_Name;
			}
			set
			{
				if ((this._Student_Name != value))
				{
					this.OnStudent_NameChanging(value);
					this.SendPropertyChanging();
					this._Student_Name = value;
					this.SendPropertyChanged("Student_Name");
					this.OnStudent_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cmp_Marks", DbType="Int")]
		public System.Nullable<int> Cmp_Marks
		{
			get
			{
				return this._Cmp_Marks;
			}
			set
			{
				if ((this._Cmp_Marks != value))
				{
					this.OnCmp_MarksChanging(value);
					this.SendPropertyChanging();
					this._Cmp_Marks = value;
					this.SendPropertyChanged("Cmp_Marks");
					this.OnCmp_MarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First_Term_marks", DbType="Int")]
		public System.Nullable<int> First_Term_marks
		{
			get
			{
				return this._First_Term_marks;
			}
			set
			{
				if ((this._First_Term_marks != value))
				{
					this.OnFirst_Term_marksChanging(value);
					this.SendPropertyChanging();
					this._First_Term_marks = value;
					this.SendPropertyChanged("First_Term_marks");
					this.OnFirst_Term_marksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Second_Term_marks", DbType="Int")]
		public System.Nullable<int> Second_Term_marks
		{
			get
			{
				return this._Second_Term_marks;
			}
			set
			{
				if ((this._Second_Term_marks != value))
				{
					this.OnSecond_Term_marksChanging(value);
					this.SendPropertyChanging();
					this._Second_Term_marks = value;
					this.SendPropertyChanged("Second_Term_marks");
					this.OnSecond_Term_marksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Final_Term_marks", DbType="Int")]
		public System.Nullable<int> Final_Term_marks
		{
			get
			{
				return this._Final_Term_marks;
			}
			set
			{
				if ((this._Final_Term_marks != value))
				{
					this.OnFinal_Term_marksChanging(value);
					this.SendPropertyChanging();
					this._Final_Term_marks = value;
					this.SendPropertyChanged("Final_Term_marks");
					this.OnFinal_Term_marksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avgg", DbType="Decimal(1,1)")]
		public System.Nullable<decimal> Avgg
		{
			get
			{
				return this._Avgg;
			}
			set
			{
				if ((this._Avgg != value))
				{
					this.OnAvggChanging(value);
					this.SendPropertyChanging();
					this._Avgg = value;
					this.SendPropertyChanged("Avgg");
					this.OnAvggChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="VarChar(10)")]
		public string Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this.OnResultChanging(value);
					this.SendPropertyChanging();
					this._Result = value;
					this.SendPropertyChanged("Result");
					this.OnResultChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Marks")]
	public partial class Mark : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _student_id;
		
		private System.Nullable<int> _Maths;
		
		private System.Nullable<int> _Phy;
		
		private System.Nullable<int> _Computer;
		
		private System.Nullable<int> _english;
		
		private System.Nullable<int> _Urdu;
		
		private System.Nullable<int> _Pak_Std;
		
		private System.Nullable<int> _First_Exam;
		
		private System.Nullable<int> _Second_Exam;
		
		private System.Nullable<int> _Final;
		
		private System.Nullable<int> _Total;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onstudent_idChanging(int value);
    partial void Onstudent_idChanged();
    partial void OnMathsChanging(System.Nullable<int> value);
    partial void OnMathsChanged();
    partial void OnPhyChanging(System.Nullable<int> value);
    partial void OnPhyChanged();
    partial void OnComputerChanging(System.Nullable<int> value);
    partial void OnComputerChanged();
    partial void OnenglishChanging(System.Nullable<int> value);
    partial void OnenglishChanged();
    partial void OnUrduChanging(System.Nullable<int> value);
    partial void OnUrduChanged();
    partial void OnPak_StdChanging(System.Nullable<int> value);
    partial void OnPak_StdChanged();
    partial void OnFirst_ExamChanging(System.Nullable<int> value);
    partial void OnFirst_ExamChanged();
    partial void OnSecond_ExamChanging(System.Nullable<int> value);
    partial void OnSecond_ExamChanged();
    partial void OnFinalChanging(System.Nullable<int> value);
    partial void OnFinalChanged();
    partial void OnTotalChanging(System.Nullable<int> value);
    partial void OnTotalChanged();
    #endregion
		
		public Mark()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int student_id
		{
			get
			{
				return this._student_id;
			}
			set
			{
				if ((this._student_id != value))
				{
					this.Onstudent_idChanging(value);
					this.SendPropertyChanging();
					this._student_id = value;
					this.SendPropertyChanged("student_id");
					this.Onstudent_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maths", DbType="Int")]
		public System.Nullable<int> Maths
		{
			get
			{
				return this._Maths;
			}
			set
			{
				if ((this._Maths != value))
				{
					this.OnMathsChanging(value);
					this.SendPropertyChanging();
					this._Maths = value;
					this.SendPropertyChanged("Maths");
					this.OnMathsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phy", DbType="Int")]
		public System.Nullable<int> Phy
		{
			get
			{
				return this._Phy;
			}
			set
			{
				if ((this._Phy != value))
				{
					this.OnPhyChanging(value);
					this.SendPropertyChanging();
					this._Phy = value;
					this.SendPropertyChanged("Phy");
					this.OnPhyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Computer", DbType="Int")]
		public System.Nullable<int> Computer
		{
			get
			{
				return this._Computer;
			}
			set
			{
				if ((this._Computer != value))
				{
					this.OnComputerChanging(value);
					this.SendPropertyChanging();
					this._Computer = value;
					this.SendPropertyChanged("Computer");
					this.OnComputerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_english", DbType="Int")]
		public System.Nullable<int> english
		{
			get
			{
				return this._english;
			}
			set
			{
				if ((this._english != value))
				{
					this.OnenglishChanging(value);
					this.SendPropertyChanging();
					this._english = value;
					this.SendPropertyChanged("english");
					this.OnenglishChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Urdu", DbType="Int")]
		public System.Nullable<int> Urdu
		{
			get
			{
				return this._Urdu;
			}
			set
			{
				if ((this._Urdu != value))
				{
					this.OnUrduChanging(value);
					this.SendPropertyChanging();
					this._Urdu = value;
					this.SendPropertyChanged("Urdu");
					this.OnUrduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pak_Std", DbType="Int")]
		public System.Nullable<int> Pak_Std
		{
			get
			{
				return this._Pak_Std;
			}
			set
			{
				if ((this._Pak_Std != value))
				{
					this.OnPak_StdChanging(value);
					this.SendPropertyChanging();
					this._Pak_Std = value;
					this.SendPropertyChanged("Pak_Std");
					this.OnPak_StdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First_Exam", DbType="Int")]
		public System.Nullable<int> First_Exam
		{
			get
			{
				return this._First_Exam;
			}
			set
			{
				if ((this._First_Exam != value))
				{
					this.OnFirst_ExamChanging(value);
					this.SendPropertyChanging();
					this._First_Exam = value;
					this.SendPropertyChanged("First_Exam");
					this.OnFirst_ExamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Second_Exam", DbType="Int")]
		public System.Nullable<int> Second_Exam
		{
			get
			{
				return this._Second_Exam;
			}
			set
			{
				if ((this._Second_Exam != value))
				{
					this.OnSecond_ExamChanging(value);
					this.SendPropertyChanging();
					this._Second_Exam = value;
					this.SendPropertyChanged("Second_Exam");
					this.OnSecond_ExamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Final", DbType="Int")]
		public System.Nullable<int> Final
		{
			get
			{
				return this._Final;
			}
			set
			{
				if ((this._Final != value))
				{
					this.OnFinalChanging(value);
					this.SendPropertyChanging();
					this._Final = value;
					this.SendPropertyChanged("Final");
					this.OnFinalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int")]
		public System.Nullable<int> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this.OnTotalChanging(value);
					this.SendPropertyChanging();
					this._Total = value;
					this.SendPropertyChanged("Total");
					this.OnTotalChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.loginn_Admin")]
	public partial class loginn_Admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _user_namee;
		
		private string _user_pass;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_nameeChanging(string value);
    partial void Onuser_nameeChanged();
    partial void Onuser_passChanging(string value);
    partial void Onuser_passChanged();
    #endregion
		
		public loginn_Admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_namee", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string user_namee
		{
			get
			{
				return this._user_namee;
			}
			set
			{
				if ((this._user_namee != value))
				{
					this.Onuser_nameeChanging(value);
					this.SendPropertyChanging();
					this._user_namee = value;
					this.SendPropertyChanged("user_namee");
					this.Onuser_nameeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_pass", DbType="VarChar(50)")]
		public string user_pass
		{
			get
			{
				return this._user_pass;
			}
			set
			{
				if ((this._user_pass != value))
				{
					this.Onuser_passChanging(value);
					this.SendPropertyChanging();
					this._user_pass = value;
					this.SendPropertyChanged("user_pass");
					this.Onuser_passChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.students")]
	public partial class student : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _student_Reg;
		
		private string _student_name;
		
		private string _student_HB;
		
		private string _students;
		
		private string _student_Payment;
		
		private System.Nullable<int> _student_Fees;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onstudent_RegChanging(int value);
    partial void Onstudent_RegChanged();
    partial void Onstudent_nameChanging(string value);
    partial void Onstudent_nameChanged();
    partial void Onstudent_HBChanging(string value);
    partial void Onstudent_HBChanged();
    partial void OnstudentsChanging(string value);
    partial void OnstudentsChanged();
    partial void Onstudent_PaymentChanging(string value);
    partial void Onstudent_PaymentChanged();
    partial void Onstudent_FeesChanging(System.Nullable<int> value);
    partial void Onstudent_FeesChanged();
    #endregion
		
		public student()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_Reg", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int student_Reg
		{
			get
			{
				return this._student_Reg;
			}
			set
			{
				if ((this._student_Reg != value))
				{
					this.Onstudent_RegChanging(value);
					this.SendPropertyChanging();
					this._student_Reg = value;
					this.SendPropertyChanged("student_Reg");
					this.Onstudent_RegChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_name", DbType="VarChar(50)")]
		public string student_name
		{
			get
			{
				return this._student_name;
			}
			set
			{
				if ((this._student_name != value))
				{
					this.Onstudent_nameChanging(value);
					this.SendPropertyChanging();
					this._student_name = value;
					this.SendPropertyChanged("student_name");
					this.Onstudent_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_HB", DbType="VarChar(50)")]
		public string student_HB
		{
			get
			{
				return this._student_HB;
			}
			set
			{
				if ((this._student_HB != value))
				{
					this.Onstudent_HBChanging(value);
					this.SendPropertyChanging();
					this._student_HB = value;
					this.SendPropertyChanged("student_HB");
					this.Onstudent_HBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_students", DbType="VarChar(50)")]
		public string students
		{
			get
			{
				return this._students;
			}
			set
			{
				if ((this._students != value))
				{
					this.OnstudentsChanging(value);
					this.SendPropertyChanging();
					this._students = value;
					this.SendPropertyChanged("students");
					this.OnstudentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_Payment", DbType="VarChar(10)")]
		public string student_Payment
		{
			get
			{
				return this._student_Payment;
			}
			set
			{
				if ((this._student_Payment != value))
				{
					this.Onstudent_PaymentChanging(value);
					this.SendPropertyChanging();
					this._student_Payment = value;
					this.SendPropertyChanged("student_Payment");
					this.Onstudent_PaymentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_Fees", DbType="Int")]
		public System.Nullable<int> student_Fees
		{
			get
			{
				return this._student_Fees;
			}
			set
			{
				if ((this._student_Fees != value))
				{
					this.Onstudent_FeesChanging(value);
					this.SendPropertyChanging();
					this._student_Fees = value;
					this.SendPropertyChanged("student_Fees");
					this.Onstudent_FeesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
